// import { Inter } from "next/font/google";
import "./globals.css";
import "flowbite";
import Sidebar from "../../component/Sidebar";
import Navbar from "../../component/Navbar";
import { PersistantProvider } from "./redux/provider";
import NavBarProvider from "./navBarProvider";
import SideBarProvider from "./sidebarProvider";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <PersistantProvider>
          {/* <NavBarProvider> */}
          <SideBarProvider>

          {/* <Navbar> */}
            {children}
            {/* </Navbar> */}
          </SideBarProvider>
            {/* </NavBarProvider> */}
        </PersistantProvider>
      </body>
    </html>
  );
}
